var couriers = [
    'AMAZON',
    'AUSTRALIA POST',
    'CANADA',
    'CANADA POST',
    'CHINA POST',
    'DHL',
    'FEDEX',
    'GLS',
    'HERMES POST',
    'HONG KONG',
    'HONGKING POST',
    'LASERSHIP',
    'NETHERLANDS POST',
    'ORNAGE',
    'POS INDONESIA',
    'ROYAL MAIL',
    'SF EXPRESS',
    'SINGAPURE',
    'SPEEDPAK',
    'SWISS',
    'TGX',
    'TNT',
    'UPS',
    'USPS'
];

var signers = [
    'CONFIRMACION SISTEMA',
    'MARTINEZ',
    'PARRALES',
    'SANCHEZ',
    'A H',
    'AJ',
    'af',
    'ALEJANDRO',
    'BOLIVAR',
    'CERON',
    'CESAR',
    'DANILO',
    'E B',
    'GARCIA',
    'hernandez',
    'J V',
    'JIEME',
    'JUAN',
    'LG',
    'MARCO',
    'MARTINEZ',
    'MEDINA',
    'PABLO',
    'RODAS',
    'ROMERO',
    'SEBASTIAN',
    'SERRON',
    'VALLEJO',
    'VARELA'
];

var costos_ruta = [41, 35, 30, 25, 20, 0];