ALTER TABLE `users` CHANGE `user_number_id` `ccid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `users` CHANGE `user_id` `cid` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `users` CHANGE `user_fname` `nombre` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `users` CHANGE `user_lname` `apellido` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `users` CHANGE `user_email` `email` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `users` CHANGE `user_mobile` `celular` INT(16) UNSIGNED NOT NULL;
ALTER TABLE `users` CHANGE `user_phone` `telefono` INT(16) UNSIGNED NOT NULL;
ALTER TABLE `users` CHANGE `user_address` `direccion` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `users` CHANGE `user_gender` `genero` VARCHAR(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `users` CHANGE `user_bday` `cumple` DATE NOT NULL;
ALTER TABLE `users` CHANGE `user_note` `comentario` VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `users` CHANGE `user_created` `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `users` CHANGE `user_tarifa` `tarifa` INT(11) NOT NULL DEFAULT '60';
RENAME TABLE `chex`.`carga` TO `chex`.`paquete`;
RENAME TABLE `chex`.`users` TO `chex`.`cliente`;
RENAME TABLE `chex`.`registro_carga` TO `chex`.`carga`;